version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - web-root:/var/www/html
    networks:
      - app-network
  app:
    container_name: authorizationservice
    build: ./

    ports:
      - "8080:8080"
    depends_on:
      - nginx
volumes:
  web-root:
networks:
  app-network:
    driver: bridge